name: HungerGames
version: '${project.version}'
main: org.namumaterial.hungergames.HungerGames
api-version: '1.18'
commands:
  kits:
    description: Show all the existing kits
    usage: /kits
  kit:
    description: Select a tributes kit
    usage: /kit [name]
  setstate:
    description: Change current game state
    usage: /change_state [state]
  state:
    description: Show game current state
    usage: /state
  gift:
    description: Spawn a gift next to you
    usage: /gift
  feast:
    description: Spawn a feast on the map
    usage: /feast
  setpopularity:
    description: Set the popularity of a player
    usage: /set_popularity [amount] where amount is a positive Integer
  popularity:
    description: Show your popularity
    usage: /popularity
  heal:
    description: Heal the player
    usage: /heal
  spawn:
    description: Teleport the player to the spawn point, the middle of the arena
    usage: /spawn
  arenaradius:
    description: Show arena radius
    usage: /arenaradius
  kitselector:
    description: Give you a kit selector
    usage: /kitselector