name: HungerGames
version: '${project.version}'
main: org.namumaterial.hungergames.HungerGames
api-version: '1.18'
commands:
  kits:
    description: Show all the existing kits
    usage: /kits
  kit:
    description: Select a tributes kit
    usage: /kit [name]
  change_state:
    description: Change current game state
    usage: /change_state [state]
  gift:
    description: Spawn a gift next to you
    usage: /gift
  set_popularity:
    description: Set the popularity of a player
    usage: /set_popularity [amount] where amount is a positive Integer
  popularity:
    description: Show your popularity
    usage: /popularity
  state:
    description: Show game current state
    usage: /state