name: HungerGames
version: '${project.version}'
main: org.namumaterial.hungergames.HungerGames
api-version: '1.18'
commands:
  kits:
    description: Show all the existing kits
    usage: /kits
  kit:
    description: Select a tributes kit
    usage: /kit [name]
